package model_view_controller;

import javax.swing.JLabel;

/**
 *
 * @author kfrey
 */
public class View extends javax.swing.JFrame implements ModelChangedEventHandler{
    private Model model;
    private Controller controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * Creates new form View1
     */
    public View(Model m, Controller c){
        this.model = m; 
        this.controller = c;
        this.model.attach(this);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        displayTxtLbl = new javax.swing.JLabel();
        userTextJPanel = new javax.swing.JPanel();
        userTextJScrollPane = new javax.swing.JScrollPane();
        userTextJTextArea = new javax.swing.JTextArea();
        cursorBtn = new javax.swing.JButton();
        computerResultJPanel = new javax.swing.JPanel();
        resultLanguageLbl = new javax.swing.JLabel();
        aiResultJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aiResponseJTextArea = new javax.swing.JTextArea();
        geminiPredLbl = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayTxtLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/display_txt.png"))); // NOI18N
        getContentPane().add(displayTxtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 50));

        userTextJPanel.setBackground(new java.awt.Color(176, 221, 253));
        userTextJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));

        userTextJScrollPane.setBackground(new java.awt.Color(176, 221, 253));

        userTextJTextArea.setBackground(new java.awt.Color(176, 221, 253));
        userTextJTextArea.setColumns(20);
        userTextJTextArea.setRows(5);
        userTextJScrollPane.setViewportView(userTextJTextArea);

        cursorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/cursor-icon.png"))); // NOI18N
        cursorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userTextJPanelLayout = new javax.swing.GroupLayout(userTextJPanel);
        userTextJPanel.setLayout(userTextJPanelLayout);
        userTextJPanelLayout.setHorizontalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTextJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userTextJPanelLayout.setVerticalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTextJPanelLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(userTextJScrollPane))
                .addContainerGap())
        );

        getContentPane().add(userTextJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 750, 120));

        computerResultJPanel.setBackground(new java.awt.Color(255, 255, 255));
        computerResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 221, 253), 5));

        resultLanguageLbl.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        resultLanguageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout computerResultJPanelLayout = new javax.swing.GroupLayout(computerResultJPanel);
        computerResultJPanel.setLayout(computerResultJPanelLayout);
        computerResultJPanelLayout.setHorizontalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultLanguageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        computerResultJPanelLayout.setVerticalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultLanguageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        getContentPane().add(computerResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 100));

        aiResultJPanel.setBackground(new java.awt.Color(176, 221, 253));
        aiResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));
        aiResultJPanel.setToolTipText("");

        aiResponseJTextArea.setBackground(new java.awt.Color(176, 221, 253));
        aiResponseJTextArea.setColumns(20);
        aiResponseJTextArea.setRows(5);
        jScrollPane1.setViewportView(aiResponseJTextArea);

        geminiPredLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        geminiPredLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        geminiPredLbl.setText("Gemini's Prediction:");
        geminiPredLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout aiResultJPanelLayout = new javax.swing.GroupLayout(aiResultJPanel);
        aiResultJPanel.setLayout(aiResultJPanelLayout);
        aiResultJPanelLayout.setHorizontalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aiResultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(aiResultJPanelLayout.createSequentialGroup()
                        .addComponent(geminiPredLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aiResultJPanelLayout.setVerticalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aiResultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geminiPredLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(aiResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 750, 170));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/bg-img2.png"))); // NOI18N
        backgroundLabel.setText("");
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursorBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(userTextJTextArea.getText());
        if(model!=null){
            model.changeTheData(userTextJTextArea.getText());  
        }
    }//GEN-LAST:event_cursorBtnActionPerformed
    
    @Override
    public void handleModelChangeEvent() {
        resultLanguageLbl.setText("Program Prediction: "+model.getThePrediction());
        displayAIResponseTxt();
    }
    
    public void displayAIResponseTxt(){
        //DISPLAYS THE RESPONSE FORM GEMINI NICELY IN THE TEXT AREA 
        String[] aiResponse = model.getGeminiResponse().split("|");
        String toPrint = "Gemini Prediction: \n";
        for(int i=0; i< aiResponse.length; i++){
            toPrint += "• "+ aiResponse[i]+"\n";
        }
        aiResponseJTextArea.setText(toPrint);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aiResponseJTextArea;
    private javax.swing.JPanel aiResultJPanel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel computerResultJPanel;
    private javax.swing.JButton cursorBtn;
    private javax.swing.JLabel displayTxtLbl;
    private javax.swing.JLabel geminiPredLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLanguageLbl;
    private javax.swing.JPanel userTextJPanel;
    private javax.swing.JScrollPane userTextJScrollPane;
    private javax.swing.JTextArea userTextJTextArea;
    // End of variables declaration//GEN-END:variables
}
