package model_view_controller;

import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author kfrey
 */
public class View extends javax.swing.JFrame implements ModelChangedEventHandler{
    private Model model;
    private Controller controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());
    boolean isImgOn;
    /**
     * Creates new form View1
     */
    public View(Model m, Controller c){
        this.model = m; 
        this.controller = c;
        this.model.attach(this);
        initComponents();
        isImgOn = false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        displayTxtLbl = new javax.swing.JLabel();
        userTextJPanel = new javax.swing.JPanel();
        userTextJScrollPane = new javax.swing.JScrollPane();
        userTextJTextArea = new javax.swing.JTextArea();
        cursorBtn = new javax.swing.JButton();
        computerResultJPanel = new javax.swing.JPanel();
        resultLanguageLbl = new javax.swing.JLabel();
        aiResultJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aiResponseJTextArea = new javax.swing.JTextArea();
        geminiPredLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        uploadImgBtn = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayTxtLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/display_txt.png"))); // NOI18N
        getContentPane().add(displayTxtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 50));

        userTextJPanel.setBackground(new java.awt.Color(176, 221, 253));
        userTextJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));

        userTextJScrollPane.setBackground(new java.awt.Color(176, 221, 253));

        userTextJTextArea.setBackground(new java.awt.Color(176, 221, 253));
        userTextJTextArea.setColumns(20);
        userTextJTextArea.setRows(5);
        userTextJScrollPane.setViewportView(userTextJTextArea);

        cursorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/cursor-icon.png"))); // NOI18N
        cursorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userTextJPanelLayout = new javax.swing.GroupLayout(userTextJPanel);
        userTextJPanel.setLayout(userTextJPanelLayout);
        userTextJPanelLayout.setHorizontalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTextJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userTextJPanelLayout.setVerticalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTextJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(userTextJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 670, 120));

        computerResultJPanel.setBackground(new java.awt.Color(255, 255, 255));
        computerResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 221, 253), 5));

        resultLanguageLbl.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        resultLanguageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout computerResultJPanelLayout = new javax.swing.GroupLayout(computerResultJPanel);
        computerResultJPanel.setLayout(computerResultJPanelLayout);
        computerResultJPanelLayout.setHorizontalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultLanguageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        computerResultJPanelLayout.setVerticalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultLanguageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        getContentPane().add(computerResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 100));

        aiResultJPanel.setBackground(new java.awt.Color(176, 221, 253));
        aiResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));
        aiResultJPanel.setToolTipText("");

        aiResponseJTextArea.setBackground(new java.awt.Color(176, 221, 253));
        aiResponseJTextArea.setColumns(20);
        aiResponseJTextArea.setRows(5);
        jScrollPane1.setViewportView(aiResponseJTextArea);

        geminiPredLbl.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        geminiPredLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        geminiPredLbl.setText("Gemini's Prediction:");
        geminiPredLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout aiResultJPanelLayout = new javax.swing.GroupLayout(aiResultJPanel);
        aiResultJPanel.setLayout(aiResultJPanelLayout);
        aiResultJPanelLayout.setHorizontalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aiResultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(aiResultJPanelLayout.createSequentialGroup()
                        .addComponent(geminiPredLbl)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        aiResultJPanelLayout.setVerticalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aiResultJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geminiPredLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(aiResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 750, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 221, 253), 5));

        uploadImgBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadImgBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/upload-arrow.png"))); // NOI18N
        uploadImgBtn.setBorder(null);
        uploadImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uploadImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uploadImgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 70, 120));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/bg-img2.png"))); // NOI18N
        backgroundLabel.setText("");
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursorBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(userTextJTextArea.getText());
        if(model!=null){
            model.changeTheData(userTextJTextArea.getText());  
        }
    }//GEN-LAST:event_cursorBtnActionPerformed

    private void uploadImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImgBtnActionPerformed
        // TODO add your handling code here:
        if(model!=null){
            model.changeTheDataImgUpload(readInIMGFile());  
        }
    }//GEN-LAST:event_uploadImgBtnActionPerformed
    
    public byte[] readInIMGFile(){
        //code borrowed then modified from TraderWindow csc260 codeshare
        //Create a file chooser
        isImgOn = true;
        byte[] imageAsBytes;
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            try{
                FileReader fr = new FileReader(fc.getSelectedFile());
                String absolutePath = fc.getSelectedFile().getAbsolutePath();
                //read in the local image into an array of bytes
                imageAsBytes = Files.readAllBytes(Paths.get(absolutePath));
                return imageAsBytes;
            }catch(IOException ex){
                JOptionPane.showMessageDialog(this, "Could not write to file", "File Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        return new byte[1];
    }
    
    
    @Override
    public void handleModelChangeEvent() {
        resultLanguageLbl.setText("Program Prediction: "+model.getThePrediction());
        displayAIResponseTxt();
        if(isImgOn){
            userTextJTextArea.setText("The image displayed: \n'"+ model.getInputtedText()+"'");
            isImgOn= false; // set it back to false after 
        }
        
    }
    
    public void displayAIResponseTxt(){
        //DISPLAYS THE RESPONSE FORM GEMINI NICELY IN THE TEXT AREA 
        String[] aiResponse = model.getGeminiResponse().split("\\|");
        String toPrint = "";
        for(int i=0; i< aiResponse.length; i++){
            toPrint += "• "+ aiResponse[i]+"\n";
        }
        aiResponseJTextArea.setText(toPrint);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aiResponseJTextArea;
    private javax.swing.JPanel aiResultJPanel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel computerResultJPanel;
    private javax.swing.JButton cursorBtn;
    private javax.swing.JLabel displayTxtLbl;
    private javax.swing.JLabel geminiPredLbl;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel resultLanguageLbl;
    private javax.swing.JButton uploadImgBtn;
    private javax.swing.JPanel userTextJPanel;
    private javax.swing.JScrollPane userTextJScrollPane;
    private javax.swing.JTextArea userTextJTextArea;
    // End of variables declaration//GEN-END:variables
}
