package model_view_controller;

import javax.swing.JLabel;

/**
 *
 * @author kfrey
 */
public class View extends javax.swing.JFrame implements ModelChangedEventHandler{
    private Model model;
    private Controller controller;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View.class.getName());

    /**
     * Creates new form View1
     */
    public View(Model m, Controller c){
        this.model = m; 
        this.controller = c;
        this.model.attach(this);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aiPredictionLabel = new javax.swing.JLabel();
        displayTxtLbl = new javax.swing.JLabel();
        userTextJPanel = new javax.swing.JPanel();
        userTextJScrollPane = new javax.swing.JScrollPane();
        userTextJTextArea = new javax.swing.JTextArea();
        cursorBtn = new javax.swing.JButton();
        computerResultJPanel = new javax.swing.JPanel();
        resultLanguageLbl = new javax.swing.JLabel();
        aiResultJPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(aiPredictionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        displayTxtLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/display_txt.png"))); // NOI18N
        getContentPane().add(displayTxtLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 50));

        userTextJPanel.setBackground(new java.awt.Color(176, 221, 253));
        userTextJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));

        userTextJScrollPane.setBackground(new java.awt.Color(176, 221, 253));

        userTextJTextArea.setBackground(new java.awt.Color(176, 221, 253));
        userTextJTextArea.setColumns(20);
        userTextJTextArea.setRows(5);
        userTextJScrollPane.setViewportView(userTextJTextArea);

        cursorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/cursor-icon.png"))); // NOI18N
        cursorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userTextJPanelLayout = new javax.swing.GroupLayout(userTextJPanel);
        userTextJPanel.setLayout(userTextJPanelLayout);
        userTextJPanelLayout.setHorizontalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addComponent(userTextJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userTextJPanelLayout.setVerticalGroup(
            userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTextJPanelLayout.createSequentialGroup()
                .addGroup(userTextJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTextJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cursorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userTextJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(userTextJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        computerResultJPanel.setBackground(new java.awt.Color(255, 255, 255));
        computerResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(176, 221, 253), 5));

        resultLanguageLbl.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        resultLanguageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout computerResultJPanelLayout = new javax.swing.GroupLayout(computerResultJPanel);
        computerResultJPanel.setLayout(computerResultJPanelLayout);
        computerResultJPanelLayout.setHorizontalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, computerResultJPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(resultLanguageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        computerResultJPanelLayout.setVerticalGroup(
            computerResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, computerResultJPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(resultLanguageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(computerResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 290, 90));

        aiResultJPanel.setBackground(new java.awt.Color(176, 221, 253));
        aiResultJPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(38, 114, 171), 5));
        aiResultJPanel.setToolTipText("");

        javax.swing.GroupLayout aiResultJPanelLayout = new javax.swing.GroupLayout(aiResultJPanel);
        aiResultJPanel.setLayout(aiResultJPanelLayout);
        aiResultJPanelLayout.setHorizontalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        aiResultJPanelLayout.setVerticalGroup(
            aiResultJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(aiResultJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 210, 190));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_images/bg_img.png"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cursorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursorBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(userTextJTextArea.getText());
        if(model!=null){
            model.changeTheData(userTextJTextArea.getText());  
        }
    }//GEN-LAST:event_cursorBtnActionPerformed
    
    @Override
    public void handleModelChangeEvent() {
        resultLanguageLbl.setText(model.getThePrediction());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new View().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiPredictionLabel;
    private javax.swing.JPanel aiResultJPanel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel computerResultJPanel;
    private javax.swing.JButton cursorBtn;
    private javax.swing.JLabel displayTxtLbl;
    private javax.swing.JLabel resultLanguageLbl;
    private javax.swing.JPanel userTextJPanel;
    private javax.swing.JScrollPane userTextJScrollPane;
    private javax.swing.JTextArea userTextJTextArea;
    // End of variables declaration//GEN-END:variables
}
